// Generated by Wrangler by running `wrangler types`

interface Env {
	CACHE: KVNamespace;
	ENVIRONMENT: "development";
	DATAFORSEO_LOGIN: string;
	DATAFORSEO_PASSWORD: string;
	CLERK_SECRET_KEY: string;
	STRIPE_SECRET_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	RESEND_API_KEY: string;
	CREDIT_LEDGER: DurableObjectNamespace<import("./src/index").CreditLedger>;
	DB: D1Database;
}
